# Generated by Django 4.2.7 on 2025-01-08 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='campaignanalytics',
            old_name='total_bounced',
            new_name='total_replied',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='content',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title',
        ),
        migrations.RemoveField(
            model_name='campaignanalytics',
            name='bounce_rate',
        ),
        migrations.RemoveField(
            model_name='campaignanalytics',
            name='click_rate',
        ),
        migrations.RemoveField(
            model_name='campaignanalytics',
            name='open_rate',
        ),
        migrations.RemoveField(
            model_name='campaignanalytics',
            name='total_delivered',
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='Untitled Campaign', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='open_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='prospects_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='response_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignanalytics',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='campaigns.campaign'),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
