# Generated by Django 4.2.7 on 2025-01-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignanalytics',
            options={'verbose_name_plural': 'Campaign Analytics'},
        ),
    ]
